"""Validation — the acceptance test for the whole pipeline. Person 1 owns
this file.

Per Prompt A5:
  1. Confusion matrix of is_defect vs (decision == "FLAG").
  2. False negatives printed separately and prominently — these are the
     metric penalized most heavily (Anomaly Detection Score).
  3. The compound-defect rows (all three parameters drifting mildly together,
     injected by generate_data.py) broken out separately — this shows whether
     Tier 3 / v_drift fusion actually catch the case they were built for.

🔵 Phase 3 — REVIEW-aware reporting (PASS/REVIEW/FLAG split):
  The confusion matrix keeps its strict definition (FLAG vs not-FLAG), but
  two additions make REVIEW legible:
  - LENIENT recall counts FLAG + REVIEW as "defect not passed": a REVIEW is
    not a miss — a human still looks at the part. Strict and lenient are
    printed side by side so nobody can hide behind the softer number.
  - Deferred defects: injected defects that landed in REVIEW are listed —
    they are handled, but it tells you how much of your recall the
    uncertainty layer (not the detectors) is carrying.
  - The compound breakdown reports PASS as missed and REVIEW as deferred.

A false negative here reflects both modules' combined behavior: if it's not
near zero, check Module A's thresholds (Z cutoff, contamination) AND Module
B's theta_slope — coordinate with your teammate rather than only tuning your
own side (§8 step 6 of the implementation doc).
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix


def validate(df: pd.DataFrame) -> dict:
    """Compute and print the validation report for the merged, decided frame.

    Requires columns: is_defect, decision (plus defect_case if generated by
    generate_data.py). Returns a dict of the headline numbers for testing.
    """
    for col in ("is_defect", "decision"):
        if col not in df.columns:
            raise KeyError(f"validate: missing required column '{col}' — "
                           f"run the full pipeline first (main.py).")

    y_true = df["is_defect"].astype(bool)
    y_pred = df["decision"] == "FLAG"
    has_review = "REVIEW" in set(df["decision"].unique())
    # Lenient view: a REVIEW is not a pass — a human still sees the part.
    not_passed = ~df["decision"].isin(["PASS"])

    cm = confusion_matrix(y_true, y_pred, labels=[False, True])
    tn, fp, fn, tp = cm.ravel()

    print("=" * 62)
    print("VALIDATION REPORT — burn-in predictive screening")
    print("=" * 62)
    print(f"\nConfusion matrix (rows=is_defect, cols=predicted FLAG):")
    print(f"               predicted PASS   predicted FLAG")
    print(f"  is_defect=False (TN): {tn:8d}      (FP): {fp:8d}")
    print(f"  is_defect=True  (FN): {fn:8d}      (TP): {tp:8d}")

    n_defects = int(y_true.sum())
    fn_rate = fn / n_defects if n_defects else 0.0
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0

    # Lenient recall: defects either FLAGged or REVIEWed (not passed).
    n_deferred = int((y_true & not_passed & ~y_pred).sum())
    lenient_recall = (tp + n_deferred) / n_defects if n_defects else 0.0

    print(f"\n  recall, strict (FLAG only): {recall:.3f}")
    if has_review:
        print(f"  recall, lenient (FLAG+REVIEW, a REVIEW is not a pass): {lenient_recall:.3f}")
    print(f"  precision (flags correct):  {precision:.3f}")
    print(f"  false negatives:            {fn} of {n_defects} defects ({fn_rate:.1%})")

    # False negatives are the metric penalized most — print them prominently.
    print("\n" + "!" * 62)
    if fn > 0:
        print(f"!! FALSE NEGATIVES: {fn} defective component(s) PASSED screening:")
        fn_rows = df[y_true & ~not_passed]
        for _, r in fn_rows.iterrows():
            case = r.get("defect_case", "?")
            print(f"!!   {r['component_id']}  lot={r.get('lot_id', '?')}  case={case}")
        print("!! Fix before calling this done: check Module A's z_threshold /")
        print("!! contamination and Module B's theta_slope (coordinate tuning).")
    else:
        print("!! FALSE NEGATIVES: 0 — every injected defect was flagged.")
    if has_review and n_deferred:
        print(f"!! DEFERRED to REVIEW: {n_deferred} defective component(s) — handled")
        print("!! by a human, but worth checking if the uncertainty layer is")
        print("!! carrying recall the detectors should.")
    print("!" * 62)

    # REVIEW breakdown — the uncertainty layer's footprint (🔵 Phase 3).
    if has_review:
        review = df[df["decision"] == "REVIEW"]
        print(f"\nREVIEW breakdown ({len(review)} deferred to a human):")
        if "reason" in review.columns:
            for bucket, label in ((review["reason"].str.contains("OOD", na=False), "OOD gate"),
                                  (review["reason"].str.contains("interval", na=False), "wide interval")):
                print(f"  {label}: {int(bucket.sum())}")
        if n_deferred:
            deferred_ids = df.loc[y_true & (df["decision"] == "REVIEW"), "component_id"].tolist()
            print(f"  defective components deferred: {', '.join(map(str, deferred_ids))}")

    # The compound case — the specific reason the fusion layers exist.
    print("\nCompound-defect breakdown (all 3 params drifting mildly together):")
    if "defect_case" in df.columns:
        compound = df[df["defect_case"] == "compound"]
        if len(compound):
            print(compound["decision"].value_counts().to_string())
            compound_missed = int((compound["decision"] == "PASS").sum())
            compound_deferred = int((compound["decision"] == "REVIEW").sum())
            if compound_missed:
                print(f"  -> {compound_missed} compound defect(s) slipped through: "
                      f"the joint/fusion layers are not doing their job — revisit")
                print(f"     IsolationForest contamination or the L2 fusion weights.")
            else:
                print("  -> all compound defects caught: fusion layers doing their job.")
            if compound_deferred:
                print(f"  -> {compound_deferred} compound defect(s) deferred to REVIEW: "
                      f"caught by the uncertainty layer, not the detectors.")
        else:
            print("  (no compound rows in this dataset)")
    else:
        print("  (defect_case column not present — skipping)")

    compound_deferred = (int((df[df["defect_case"] == "compound"]["decision"] == "REVIEW").sum())
                         if "defect_case" in df.columns else None)
    return {
        "tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp),
        "recall": recall, "precision": precision,
        "lenient_recall": lenient_recall,
        "n_review": int((df["decision"] == "REVIEW").sum()),
        "deferred_defects": n_deferred,
        "compound_missed": int((df[df["defect_case"] == "compound"]["decision"] == "PASS").sum())
        if "defect_case" in df.columns else None,
        "compound_deferred": compound_deferred,
    }


if __name__ == "__main__":
    # Convenience entrypoint: validate a previously saved full pipeline output.
    import sys
    if len(sys.argv) != 2:
        print("usage: python validate.py <merged_output.csv>")
        raise SystemExit(1)
    validate(pd.read_csv(sys.argv[1]))
